server:
  port: 9001
spring:
  application:
    name: ytd_base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/p2p?characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true