server:
  port: 9009
spring:
  application:
    name: ytd-sms
  rabbitmq:
    host: 192.168.217.136
aliyun:
  sms:
    accessKeyId: LTAIxo9ZQy1tSHYL
    accessKeySecret: IawJXWPqlMvG69lzCcEOBoyvGvwE5G
    template_code: SMS_94700095
    sign_name: 巴拉拉小魔仙自己做短信测试